// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairingTest.API.Infrastructure.Data;

namespace PairingTest.API.Infrastructure.Migrations
{
    [DbContext(typeof(PairingTestDBContext))]
    [Migration("20210301222146_SeedData2")]
    partial class SeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PairingTest.API.Core.Entities.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuestionnaireTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            QuestionnaireTitle = "Geography Questions"
                        });
                });

            modelBuilder.Entity("PairingTest.API.Core.Entities.QuestionOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("QuestionID")
                        .HasColumnType("bigint");

                    b.Property<string>("QuestionsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionID");

                    b.ToTable("QuestionOption");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            QuestionID = 1L,
                            QuestionsText = "What is the capital of Cuba?"
                        },
                        new
                        {
                            Id = 2L,
                            QuestionID = 1L,
                            QuestionsText = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 3L,
                            QuestionID = 1L,
                            QuestionsText = "What is the capital of Poland?"
                        },
                        new
                        {
                            Id = 4L,
                            QuestionID = 1L,
                            QuestionsText = "What is the capital of Germany?"
                        });
                });

            modelBuilder.Entity("PairingTest.API.Core.Entities.QuestionOption", b =>
                {
                    b.HasOne("PairingTest.API.Core.Entities.Question", "QuestionOptionQuestion")
                        .WithMany("QuestionOption")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionOptionQuestion");
                });

            modelBuilder.Entity("PairingTest.API.Core.Entities.Question", b =>
                {
                    b.Navigation("QuestionOption");
                });
#pragma warning restore 612, 618
        }
    }
}
